version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - es
  - en
words:
  - colbreak
  - Renderizamos
  - Renderizar
  - subquestion
  - trunc
  - Typst
ignoreWords: []
import: []
