version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - es
  - en
words:
  - colbreak
  - emph
  - euclid
  - github
  - linux
  - pagebreak
  - renderizamos
  - renderizar
  - shiroa
  - spacex
  - strfmt
  - subquestion
  - subquestions
  - trunc
  - typst
ignoreWords: []
import: []
