version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries:
  - es
  - en
words:
  - colbreak
  - euclid
  - renderizamos
  - renderizar
  - strfmt
  - subquestion
  - trunc
  - typst
ignoreWords: []
import: []
