[package]
name = "g-exam"
version = "0.1.0"
entrypoint = "g-exam.typ"
authors = ["Andrés Giménez Muñoz"]
license = "MIT"
keyworks=["exam, question"]
repository="https://github.com/MatheSchool/typst-g-Exam"
description = "Template for creating exams."