[en]
grade-table-queston = "Question"
grade-table-total = "Total"
grade-table-points = "Points"
grade-table-grade = "Grade"
point = "point"
points = "points"
page = "Page"
page-counter-display = "1 of 1"
family-name = "Surname"
given-name = "Name"
group = "Group"
date = "Date"

[es]
grade-table-queston = "Pregunta"
grade-table-total = "Total"
grade-table-points = "Puntos"
grade-table-grade = "Qualification"
point = "punto"
points = "puntos"
page = "Página"
page-counter-display = "1 de 1"
family-name = "Apellidos"
given-name = "Nombre"
group = "Grupo"
date = "Fecha"

[de]
grade-table-queston = "Frage"
grade-table-total = "Gesamt"
grade-table-points = "Punkte"
grade-table-grade = "Verkalkung"
point = "point"
points = "points"
page = "Seite"
page-counter-display = "1 von 1"
family-name = "Nachname"
given-name = "Vor-und"
group = "Gruppe"
date = "Datum"

[fr]
grade-table-queston = "Question"
grade-table-total = "Totale"
grade-table-points = "Aiguillage"
grade-table-grade = "Calivage"
point = "point"
points = "points"
page = "Page"
page-counter-display = "1 sur 1"
family-name = "Nom"
given-name = "Prénom"
group = "Groupe"
date = "Date"

[pt]
grade-table-queston = "Perguntas"
grade-table-total = "Total"
grade-table-points = "Pontos"
grade-table-grade = "calificação"
point = "ponto"
points = "pontos"
page = "Página"
page-counter-display = "1 de 1"
family-name = "Apelido"
given-name = "Nome"
group = "Grupo"
date = "Data"

[it]
grade-table-queston = "Domande"
grade-table-total = "Totale"
grade-table-points = "Punti"
grade-table-grade = "Calificazione"
point = "punto"
points = "punti"
page = "Pagina"
page-counter-display = "1 di 1"
family-name = "Cognome"
given-name = "Nome"
group = "Gruppo"
date = "Dattero"

[nl]
grade-table-queston = "Vraag"
grade-table-total = "Totaal"
grade-table-points = "Punten"
grade-table-grade = "Score"
point = "punt"
points = "punten"
page = "pg."
page-counter-display = "1 / 1"
family-name = "Achternaam"
given-name = "Voornaam"
group = "Groep"
date = "Datum"
