name: g-exam::gh_pages
on:
  push:
    paths: 
      - 'docs-shiroa/**'
      - 'examples/**'

permissions:
  pages: write
  id-token: write
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Delete samples and test
        run: |
          rm -rf ./examples/*.pdf
          rm -rf ./test/*.pdf
      
      - name: Download font assets
        run: |
          mkdir -p assets/fonts/
          curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.1.0/charter-font-assets.tar.gz | tar -xvz -C assets/fonts/
          curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.1.5/source-han-serif-font-assets.tar.gz | tar -xvz -C assets/fonts/
      
      - name: Download & install shiroa
        run: |
          curl -L https://github.com/Myriad-Dreamin/shiroa/releases/download/v0.3.1-rc4/shiroa-x86_64-unknown-linux-gnu.tar.gz | tar -xvz
          chmod +x shiroa-x86_64-unknown-linux-gnu/shiroa
          sudo cp shiroa-x86_64-unknown-linux-gnu/shiroa /usr/bin/shiroa
      
      - name: Build Book
        run: |
          shiroa build --font-path assets/fonts --path-to-root /typst-g-exam/ --workspace . docs-shiroa/g-exam-doc --mode static-html
          
      - uses: typst-community/setup-typst@v4

      - name: Compile Typst examples to PDF
        shell: bash
        run: |
          for archivo in $(ls -1 ./examples/*.typ); do
              echo "$archivo"
              typst compile $archivo --root .
              
              if [ $? -eq 0 ]; then
                  echo "Compilación exitosa: $archivo"
              else
                  echo "Error al compilar: $archivo"
              fi
          done

      - name: Copy examples PDF
        shell: bash
        run: |
          cp ./examples/*.pdf ./docs-shiroa/dist/assets/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload `/github-pages` sub directory
          path: './docs-shiroa/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
