name: Build Typst document (CI)
on: 
  push:
    paths: 
    - 'src/**/*.typ'
    - 'examples/**/*.typ'
    - 'test/**/*.typ'
    - '**/*.yaml'
    - '**/*.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Delete samples and test
        run: |
          rm -rf ./examples/*.pdf
          rm -rf ./test/*.pdf
      
      - uses: typst-community/setup-typst@v3

      - name: Compile Typst examples to PDF
        shell: bash
        run: |
          cd ./examples/
          
          find "$directorio_base" -type f -name "*.typ" | while IFS= read -r archivo; do
          typst compile "$archivo"
            
          if [ $? -eq 0 ]; then
              echo "Compilación exitosa: $archivo"
          else
              echo "Error al compilar: $archivo"
          fi
          done

      # - name: Compile Typst examples to PDF
      #   shell: bash
      #   run: |
      #     cd ./examples/
      #     for file in $(ls -1 *.typ); do
      #       typst compile "$file"
      #     done

      # - name: List Files examples
      #   id: file-list-examples
      #   shell: bash
      #   run: |
      #     listexamples=$(ls -1 ./examples/*.typ);
      #     file_list_examples=$(echo "$listexamples" | sed ':a;N;$!ba;s/\n/ /g')
      #     echo "File List Examples: $file_list_examples"
      #     echo "file_list_examples=$file_list_examples" >> $GITHUB_OUTPUT

      # - name: Compile Typst examples to PDF
      #   uses: mkpoli/compile-typst-action@main
      #   with:
      #     source_paths: ${{ steps.file-list-examples.outputs.file_list_examples }} 
      #     root_path: '.' 

      # - name: Compile Typst examples to PDF
      #   uses: lvignoli/typst-action@v0
      #   with:
      #     source_file: ${{ steps.file-list-examples.outputs.file_list_examples }} 

      # - name: List Files test
      #   id: file-list-test
      #   shell: bash
      #   run: |
      #     listtest=$(ls -1 ./test/**/*.typ);
      #     file_list_test=$(echo "$listtest" | sed ':a;N;$!ba;s/\n/ /g')
      #     echo "File List Test: $file_list_test"
      #     echo "file_list_test=$file_list_test" >> $GITHUB_OUTPUT
  
      # - name: Typst
      #   uses: lvignoli/typst-action@main
      #   with:
      #     source_file: |
      #       test/questions/test-001-question.typ
      #       test/questions/test-002-subquesstion.typ
      #       test/questions/test-003-only-usbquestion.typ


      # - name: Compile Typst test to PDF
      #   uses: mkpoli/compile-typst-action@main
      #   with:
      #     source_paths: ${{ steps.file-list-test.outputs.file_list_test }}
      #     root_path: '.' 
      # - name: Compile Typst test to PDF
      #   uses: lvignoli/typst-action@v0
      #   with:
      #     source_file: ${{ steps.file-list-test.outputs.file_list_test }}

      - name: Compile Typst test to PDF
        shell: bash
        run: |
          for file in $(ls -1 ./test/**/*.typ); do
            typst compile "$file"
          done

      - name: Delete Doc
        run: |
          rm -rf ./manual/*.pdf

      - name: Compile documentation to PDF
        uses: lvignoli/typst-action@main
        with:
          source_file: "manual/g-exam-manual.typ"

      - name: Upload examples PDF file
        uses: actions/upload-artifact@v3
        with:
          name: examples-g-exam
          path: ./examples/*.pdf

      - name: Upload documentation PDF file
        uses: actions/upload-artifact@v3
        with:
          name: document-g-exam
          path: ./manual/*.pdf