name: Build Typst document (CI)
on: 
  push:
    paths: 
    - 'src/**/*.typ'
    - 'examples/**/*.typ'
    - 'test/**/*.typ'
    - '**/*.yaml'
    - '**/*.toml'
    - '!docs-shiroa/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
     
      - name: Delete samples and test
        run: |
          rm -rf ./examples/*.pdf
          rm -rf ./test/*.pdf
      
      - uses: typst-community/setup-typst@v4

      - name: Compile Typst examples to PDF
        shell: bash
        run: |
          for archivo in ./examples/*.typ; do
              echo "$archivo"
              typst compile $archivo --root .
              
              if [ $? -eq 0 ]; then
                  echo "Compilación exitosa: $archivo"
              else
                  echo "Error al compilar: $archivo"
              fi
          done

      - name: Compile Typst test to PDF
        shell: bash
        run: |
          for archivo in ./test/**/*.typ; do
            echo "$archivo"
            typst compile $archivo --root .
            
            if [ $? -eq 0 ]; then
                echo "Compilación exitosa: $archivo"
            else
                echo "Error al compilar: $archivo"
            fi
          done

      - name: Upload examples PDF file
        uses: actions/upload-artifact@v4
        with:
          name: examples-g-exam
          path: ./examples/*.pdf

      - name: Upload examples PDF file
        uses: actions/upload-artifact@v4
        with:
          name: test-g-exam
          path: ./test/**/*.pdf
          