name: Build Typst document (CI)
on: 
  push:
    # paths: '**/*.typ'
  workflow_dispatch:
    # paths: '**/*.typ'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - uses: typst-community/setup-typst@v3
        with:
          version: latest

      - name: Delete samples
        run: |
          rm -rf ./examples/*.pdf

      # - name: Compile Typst to PDF
      #   uses: mkpoli/compile-typst-action@main
      #   with:
      #     source_paths: "examples/exam-001.typ examples/exam-002.typ examples/exam-003.typ examples/exam-005.typ"
      #     root_path: '.'

      # - name: Compile Typst to PDF
      #   uses: mkpoli/compile-typst-action@main
      #   with:
      #     source_paths: "examples/exam-localization.typ examples/exam-minimal.typ examples/exam-points-position.typ"
      #     root_path: '.' 

      - name: List Files
        id: file-list
        shell: bash
        run: |
          list=$(ls -1 /examples/*.typ);
          matrix_values=$(echo '[ "'"$(echo "$list" | sed ':a;N;$!ba;s/\n/", "/g')"'" ]')
          echo "Matrix values: $matrix_values"
          echo "matrix_values=$matrix_values" >> $GITHUB_OUTPUT
        # run: ls examples/*.typ >> $GITHUB_OUTPUT

      # - name: Echo 1
      #   STEP_OUTPUT: ${{ steps.file-list.outputs.stdout }}
      #   shell: bash
      #   run: echo ${{ steps.file-list.outputs.stdout }}

      - name: Echo 1.2      
        shell: bash
        run: echo ${{ steps.file-list.outcome  }}

      # - name: Get all yaml files
      #   id: file-list
      #   uses: the-coding-turtle/ga-file-list@v0.1
      #   with:
      #     directory: "examples"
      #     file_extension: "typ"

      - name: Echo 1.2      
        shell: bash
        run: echo ${{ steps.file-list.outputs.stdout  }}

      # - name: List Files2
      #   id: file-list2
      #   shell: bash
      #   run: ls examples/*.typ >> "$GITHUB_OUTPUT"

      # - name: Echo 2.2
      #   shell: bash
      #   run: echo ${{ steps.file-list2.outputs.stdout }}


      - name: Compile Typst to PDF
        uses: mkpoli/compile-typst-action@main
        with:
          source_paths: ${{ steps.file-list.outputs.stdout }}
          root_path: '.' 

      - name: Compile documentation to PDF
        uses: mkpoli/compile-typst-action@main
        with:
          source_paths: "documentation/document.typ"
          root_path: '.' 

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: examples-g-exam
          path: ./examples/*.pdf
