name: Build Typst document (CI)
on: 
  push:
    paths: 
    - 'src/**/*.typ'
    - 'examples/**/*.typ'
    - 'test/**/*.typ'
    - '**/*.yaml'
    - '**/*.toml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Delete samples and test
        run: |
          rm -rf ./examples/*.pdf
          rm -rf ./test/*.pdf
      
      - uses: typst-community/setup-typst@v3

      - name: Compile Typst examples to PDF
        shell: bash
        run: |
          for archivo in $(ls -1 ./examples/*.typ); do
              echo "$archivo"
              typst compile $archivo --root .
              
              if [ $? -eq 0 ]; then
                  echo "Compilación exitosa: $archivo"
              else
                  echo "Error al compilar: $archivo"
              fi
          done

      - name: Compile Typst test to PDF
        shell: bash
        run: |
          for archivo in $(ls -1 ./test/**/*.typ); do
            echo "$archivo"
            typst compile $archivo --root .
            
            if [ $? -eq 0 ]; then
                echo "Compilación exitosa: $archivo"
            else
                echo "Error al compilar: $archivo"
            fi
          done

      # - name: Delete Doc
      #   run: |
      #     rm -rf ./manual/*.pdf

      # - name: Compile documentation to PDF
      #   shell: bash
      #   run: |
      #     typst compile ./manual/g-exam-manual.typ --root .

      - name: Upload examples PDF file
        uses: actions/upload-artifact@v4
        with:
          name: examples-g-exam
          path: ./examples/*.pdf

      - name: Upload examples PDF file
        uses: actions/upload-artifact@v4
        with:
          name: test-g-exam
          path: ./test/**/*.pdf

      # - name: Upload documentation PDF file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: document-g-exam
      #     path: ./manual/*.pdf